file(READ "${INPUT}" hex HEX)
string(REGEX MATCHALL "([A-Fa-f0-9][A-Fa-f0-9])" bytes "${hex}")
set(out "#pragma once\n#include <cstddef>\nstatic const unsigned char ${NAME}[] = {")
set(i 0)
foreach(b IN LISTS bytes)
    if(i GREATER 0)
        string(APPEND out ",")
    endif()
    string(APPEND out "0x${b}")
    math(EXPR i "${i} + 1")
endforeach()
string(APPEND out "};\nstatic const size_t ${NAME}_len = ${i};\n")
file(WRITE "${OUTPUT}" "${out}")
